[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

[target.aarch64-pc-windows-msvc]
linker = "lld"

[build]
# Uncomment to set a default target
# target = "x86_64-unknown-linux-gnu"
